""""""""""""""""""""""""""""""""""""""""""""""""""""
" Vim configuration
"
" Author: Roy Portas - www.royportas.com
" Version 2.0
""""""""""""""""""""""""""""""""""""""""""""""""""""

let vimplug_exists=expand('~/.vim/autoload/plug.vim')

if !filereadable(vimplug_exists)
	echo "Installing Vim-Plug..."
	echo ""
	silent !\curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	let g:not_finish_vimplug = "yes"

	autocmd VimEnter * PlugInstall
endif

call plug#begin(expand('~/.vim/plugged'))
Plug 'airblade/vim-gitgutter'                     " Display git on the gutter
Plug 'ctrlpvim/ctrlp.vim'                         " File searching
Plug 'ervandew/supertab'                          " Autocompletion
Plug 'itchyny/lightline.vim'                      " Custom statusbar (Requires 256 bit colours)
Plug 'chriskempson/base16-vim'                    " Base 16 Colorschemes
Plug 'Yggdroot/indentLine'                        " Indentation guides

" Coding style and quality
Plug 'vim-syntastic/syntastic'                    " Syntastic
Plug 'editorconfig/editorconfig-vim'              " Allows project based vim configurations

" Language Plugins
Plug 'keith/swift.vim'                            " Swift language
Plug 'othree/html5.vim' 			  " HTML5 language
Plug 'posva/vim-vue'                              " Vue language support
Plug 'ap/vim-css-color'                           " CSS colouring
call plug#end()

" Ctrl P ignore config
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows

" Ignore the following directories and files
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.git|\.hg|\.svn|vendor|node_modules)$',
  \ 'file': '\v\.(exe|so|dll)$'
  \ }

" Ignore files in the .gitignore
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']

" Syntastic
let g:syntastic_check_on_wq = 0
let g:syntastic_check_on_open = 0
let g:syntastic_xml_xmllint_args = "--xinclude --postvalid --nonet"

" Syntastic checkers
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_swift_checkers = ['swiftlint']
let g:syntastic_vue_checkers = ['eslint']

" Disable concealing characters (i.e. JSON)
set cole = 0

" Set the background color
"set background=light

" Keyboard shortcuts
:inoremap jj <esc>

" Allow system clipboard
set clipboard=unnamed

" Enable syntax highlighting
syntax enable

" Better block indenting
vnoremap > >gv
vnoremap < <gv

" Enable caching
set hidden

" Line numbering
set number
set numberwidth=5

" Allow mouse input
set mouse = a

" 1 tab == 4 spaces
set expandtab
set softtabstop=4
set tabstop=4
set shiftwidth=4

" Autoindent stuff
set ai
set si
set wrap

" Command line completion
set wildmenu
set showcmd

" Always show the current position
set ruler

" Always show status line
set laststatus=2

" Search configuration
set incsearch
set hlsearch
set ignorecase

" Highlight matching brackets
set showmatch

" Disable backups
set nobackup
set nowritebackup
set noswapfile

" Automatically reload the file when it is changed
set autoread

" Fix backspace
set backspace=indent,eol,start

" Show the current mode
set showmode

" Set paste toggle
set pastetoggle=<F11>


" Define how split works
set splitbelow
set splitright

" Set colour column
" set colorcolumn=80

" Set the indent guide colour to a darker grey
let g:indentLine_color_term = 239

" Set the color scheme
colorscheme base16-ocean

" Setup gvim options
if has("gui_running")
    set anti enc=utf-8
    set guifont=Source\ Code\ Pro:h11
end

" Hide the duplicated data caused by lightline
set noshowmode

" Filetype plugins
filetype plugin indent on
